### ISSUE TITLE
Create VM template system for quick deployment

### ISSUE THREAD

**Issue by darkstormgames** [darkstormgames/rollo_site#20]
## Description
Develop a comprehensive VM template system that allows users to create, manage, and deploy virtual machines from predefined configurations and OS images. This speeds up VM deployment and ensures consistency.

### Template Types
1. **OS Templates**
   - Ubuntu 20.04/22.04/24.04
   - Debian 11/12
   - CentOS Stream 8/9
   - Windows Server 2012/2016
   - Windows 7/8.1/10/11
   - Custom OS images

2. **Application Templates**
   - LAMP stack
   - Docker host
   - Kubernetes node
   - Database server
   - Web server

3. **Resource Templates**
   - Development (light resources)
   - Production (balanced)
   - High-performance (max resources)
   - Custom configurations

### Template Features
- Base OS image management
- Pre-installed software packages
- Network configuration presets
- Security hardening options
- Cloud-init support
- Startup scripts

## Image Management
- Upload custom images
- Import from URLs
- Image versioning
- Compression support
- Integrity verification
- Storage optimization

### Template Structure
```yaml
template:
  id: "ubuntu-22-04-web"
  name: "Ubuntu 22.04 Web Server"
  description: "Ubuntu with nginx pre-installed"
  os:
    type: "linux"
    distro: "ubuntu"
    version: "22.04"
  image:
    source: "https://cloud-images.ubuntu.com/..."
    checksum: "sha256:..."
    format: "qcow2"
  resources:
    cpu: 2
    memory: 4096
    disk: 40
  packages:
    - nginx
    - php-fpm
    - mysql-client
  cloud_init:
    user_data: |
      #cloud-config
      packages:
        - nginx
```

## Tasks
- [ ] Design template database schema
- [ ] Create template management API
- [ ] Implement image storage system
- [ ] Add image upload/import functionality
- [ ] Create template builder UI
- [ ] Implement cloud-init support
- [ ] Add template versioning
- [ ] Create template marketplace
- [ ] Build deployment wizard
- [ ] Add customization options
- [ ] Implement validation system
- [ ] Create template documentation

## API Endpoints
- `GET /api/templates` - List all templates
- `GET /api/templates/{id}` - Get template details
- `POST /api/templates` - Create new template
- `PUT /api/templates/{id}` - Update template
- `DELETE /api/templates/{id}` - Delete template
- `POST /api/templates/{id}/deploy` - Deploy VM from template
- `POST /api/images/upload` - Upload OS image
- `GET /api/templates/{id}/versions` - Get template versions

## Template Deployment Flow
1. Select template
2. Customize resources
3. Configure networking
4. Set hostname/credentials
5. Review configuration
6. Deploy VM
7. Run cloud-init
8. Verify deployment

## Acceptance Criteria
- Templates can be created and managed
- OS images upload and store correctly
- VMs deploy from templates successfully
- Cloud-init configurations work
- Template versioning tracks changes
- UI provides easy template selection
